dist: trusty
sudo: required

language: node_js
node_js:
  - "4"
  - "6"
  - "8"

env:
  global:
    - POSTGRES_URL=postgres://postgres@127.0.0.1:5432/travis_ci_test
    - MYSQL_URL=mysql://root@127.0.0.1/test

services:
  - postgresql
  - mysql

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
  postgresql: "9.6"

before_install:
  - mysql -e 'SET PASSWORD FOR "root"@"localhost" = PASSWORD("");' -uroot
  - mysql -e "create database test"
  - psql -c 'create database travis_ci_test;' -U postgres

script: npm run coverage:ci

notifications:
  email: false