/* tslint:disable */

export type format_enum = 'html' | 'markdown' | 'text';
export type user_status_enum = 'active' | 'confirmed' | 'deleted' | 'pending' | 'suspended';

export namespace UsersFields {
    export type email = string;
    export type id = number;
    export type pass_crypt = string;
    export type creation_time = Date;
    export type display_name = string;
    export type data_public = boolean;
    export type description = string;
    export type home_lat = number | null;
    export type home_lon = number | null;
    export type home_zoom = number | null;
    export type nearby = number | null;
    export type pass_salt = string | null;
    export type image_file_name = string | null;
    export type email_valid = boolean;
    export type new_email = string | null;
    export type creation_ip = string | null;
    export type languages = string | null;
    export type status = user_status_enum;
    export type terms_agreed = Date | null;
    export type consider_pd = boolean;
    export type preferred_editor = string | null;
    export type terms_seen = boolean;
    export type auth_uid = string | null;
    export type description_format = format_enum;
    export type image_fingerprint = string | null;
    export type changesets_count = number;
    export type traces_count = number;
    export type diary_entries_count = number;
    export type image_use_gravatar = boolean;
    export type image_content_type = string | null;
    export type auth_provider = string | null;
    export type uuid_column = string | null;
    export type number_ = number | null;
    export type string_ = string | null;
    export type money_col = number | null;
    export type char_col = string | null;
    export type time_col = string | null;
    export type inet_col = string | null;
    export type jsonb_col = Object | null;
    export type numeric_col = number | null;
    export type bytea_col = string | null;
    export type bool_array_col = Array<boolean> | null;
    export type varchar_array_col = Array<string> | null;
    export type int2_array_col = Array<number> | null;
    export type int4_array_col = Array<number> | null;
    export type int8_array_col = Array<number> | null;
    export type uuid_array_col = Array<string> | null;
    export type text_array_col = Array<string> | null;
    export type bytea_array_col = Array<string> | null;
    export type real_col = number | null;
    export type double_col = number | null;
    export type time_with_tz = string | null;
    export type oid_col = number | null;
    export type interval_col = string | null;
    export type json_col = Object | null;
    export type date_col = Date | null;
    export type unspported_path_type = any | null;
    export type name_type_col = string | null;
    export type json_array_col = Array<Object> | null;
    export type jsonb_array_col = Array<Object> | null;
    export type timestamptz_array_col = Array<Date> | null;

}

export interface users {
    email: UsersFields.email;
    id: UsersFields.id;
    pass_crypt: UsersFields.pass_crypt;
    creation_time: UsersFields.creation_time;
    display_name: UsersFields.display_name;
    data_public: UsersFields.data_public;
    description: UsersFields.description;
    home_lat: UsersFields.home_lat;
    home_lon: UsersFields.home_lon;
    home_zoom: UsersFields.home_zoom;
    nearby: UsersFields.nearby;
    pass_salt: UsersFields.pass_salt;
    image_file_name: UsersFields.image_file_name;
    email_valid: UsersFields.email_valid;
    new_email: UsersFields.new_email;
    creation_ip: UsersFields.creation_ip;
    languages: UsersFields.languages;
    status: UsersFields.status;
    terms_agreed: UsersFields.terms_agreed;
    consider_pd: UsersFields.consider_pd;
    preferred_editor: UsersFields.preferred_editor;
    terms_seen: UsersFields.terms_seen;
    auth_uid: UsersFields.auth_uid;
    description_format: UsersFields.description_format;
    image_fingerprint: UsersFields.image_fingerprint;
    changesets_count: UsersFields.changesets_count;
    traces_count: UsersFields.traces_count;
    diary_entries_count: UsersFields.diary_entries_count;
    image_use_gravatar: UsersFields.image_use_gravatar;
    image_content_type: UsersFields.image_content_type;
    auth_provider: UsersFields.auth_provider;
    uuid_column: UsersFields.uuid_column;
    number: UsersFields.number_;
    string: UsersFields.string_;
    money_col: UsersFields.money_col;
    char_col: UsersFields.char_col;
    time_col: UsersFields.time_col;
    inet_col: UsersFields.inet_col;
    jsonb_col: UsersFields.jsonb_col;
    numeric_col: UsersFields.numeric_col;
    bytea_col: UsersFields.bytea_col;
    bool_array_col: UsersFields.bool_array_col;
    varchar_array_col: UsersFields.varchar_array_col;
    int2_array_col: UsersFields.int2_array_col;
    int4_array_col: UsersFields.int4_array_col;
    int8_array_col: UsersFields.int8_array_col;
    uuid_array_col: UsersFields.uuid_array_col;
    text_array_col: UsersFields.text_array_col;
    bytea_array_col: UsersFields.bytea_array_col;
    real_col: UsersFields.real_col;
    double_col: UsersFields.double_col;
    time_with_tz: UsersFields.time_with_tz;
    oid_col: UsersFields.oid_col;
    interval_col: UsersFields.interval_col;
    json_col: UsersFields.json_col;
    date_col: UsersFields.date_col;
    unspported_path_type: UsersFields.unspported_path_type;
    name_type_col: UsersFields.name_type_col;
    json_array_col: UsersFields.json_array_col;
    jsonb_array_col: UsersFields.jsonb_array_col;
    timestamptz_array_col: UsersFields.timestamptz_array_col;
}
